### ISSUE TITLE
FFI?

### ISSUE THREAD

**Issue by technomancy** [ryansuchocki/microscheme#2]
I would like to write some scheme that calls out to existing C libraries. I don't see anything in the examples about this. How much work would it be to add, and what would it look like?

**Comment by technomancy** [comment]
I'm happy to close this out as it's got everything I need, but maybe we could replace it with some other issues that have more specific features, like doing type conversions on FFI calls.

**Comment by ryansuchocki** [comment]
Sure.

Have you seen ffi_stuff/microscheme_types.c and ffi_stuff/ffitest.c?

microscheme_types.c defines the microscheme types precisely in C. ffitest.c shows how you can then recurse through microscheme data structures easily from the C side...

Now we can say that any C function called through the FFI should take up to 10 arguments of type ms_value, and return one ms_value. All type conversion is done on the C side via microscheme_types.c. I think this is a very nice arrangement, because the C type checker will enforce all necessary type conversion.

**Comment by technomancy** [comment]
Oh gotcha; very cool. That wasn't exactly what I was thinking, but I'm happy with that arrangement too.
